### ISSUE TITLE
doesn't work !

### ISSUE THREAD

**Issue by louisdoe** [theJenix/diawi-cli#3] opened 2016-01-26 13:31 UTC
Hi

sorry but it doesn't work.

I am on ubunut 14.04.

Here's the error I get: 

```
$ diawi-cli -c "tu peux essayer ça stp ?" -e philippe.sabuco@gmail.co BoardL
ine.ipa 
Uploading BoardLine.ipa as GS8MQSVA2FHXP1IUIK7TDAZ1QA8OU.ipa...
Traceback (most recent call last):
  File "/home/louisro/diawi-cli/diawi-cli", line 51, in <module>
    {'Content-Type': 'application/octet-stream'}))
  File "/home/louisro/diawi-cli/diawi-cli", line 21, in do_request
    return urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

**Comment by theJenix** [comment] 2016-01-26 14:12
Hey thanks for letting me know, and sorry about that.  I'll see if I can fix it ASAP.

**Comment by theJenix** [comment] 2016-01-26 15:41
It looks like diawi.com switched to using https.  I changed the http urls to https and it works when I run it through a proxy, but not directly.  This is apparently an openssl problem (I'm on Mac OS X El Capitan but it also can happen with Ubuntu).  I'm still working on this, but I went ahead and pushed the change: if you want, you can try it out.

**Comment by theJenix** [comment] 2016-01-26 16:21
Just pushed a change that seems to work in all situations for me.  It looks like Diawi.com switched their web server to only support TLS 1.2 and above, so I had to change the code to force that SSL version.  Updated the readme.md to note these changes and issues with Mac OS X default python version.  Please pull the latest and let me know if it all works!

**Comment by louisdoe** [comment] 2016-01-27 08:25
Hi Jesse

thanks for your messages :)

I still get an error with the last commit on master:

```
$ diawi-cli -c "tu peux essayer ça stp ?" -e louisromain@yahoo.fr BoLine.ipa 
Uploading BoardLine.ipa as XVTKCKDEREGGC6N7RXK0CUBWHM155.ipa...
Traceback (most recent call last):
  File "/home/louisro/diawi-cli-master/diawi-cli", line 99, in <module>
    'Content-Length': len(theFile)}))
  File "/home/louisro/diawi-cli-master/diawi-cli", line 63, in do_request
    return urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/home/louisro/diawi-cli-master/diawi-cli", line 48, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=ssl.PROTOCOL_TLSv1_2)
`̀``
```

**Comment by theJenix** [comment] 2016-01-27 14:37
The bottom of the error is cut off in the text, but I suspect it's because you're using an old Python version.  Do you see the text "AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'" when you run this on your computer?  If so, you will need to upgrade your Python version to at least 2.7.9 (when that protocol version was added).  Sorry about that, I should have clarified in the previous comment.

**Comment by theJenix** [comment] 2016-01-27 14:49
I just made a change to the script to test for this and print out an explanation.  That alone wont fix your problem (you still need to upgrade your python version to one that supports TLS v1.2) but it should clear up confusion for future users.

**Comment by louisdoe** [comment] 2016-01-27 21:07
Whoa, seems complicated. My version of python is 2.7.6, but I also have
python3 installed (Ubuntu 14.04).

If python3 works with your code, would it be possible to make it choose
python3 instead of python ?

Thanks

2016-01-27 15:49 GMT+01:00 Jesse Rosalia notifications@github.com:

**Comment by theJenix** [comment] 2016-01-27 21:13
Yea, sorry about the complexity...unfortunately the SSL stuff is out of my hands.  I haven't tested this with python3, but if it works (or works with small tweaks), I don't see why not.

**Comment by louisdoe** [comment] 2016-01-27 22:56
ok no pb, it's not your fault !
Do you know how can I make my $python command call another version of
python ? or install python 2.7.9 in here ? It doesn't seem quite simple,
that's why I was talking about complexity

2016-01-27 22:13 GMT+01:00 Jesse Rosalia notifications@github.com:

**Comment by theJenix** [comment] 2016-01-28 14:38
If you aren't held to version 2.7.6 for any reason, I would try to upgrade using apt-get (the Ubuntu package manager)..it looks like the latest version on apt is 2.7.9 which should work.  If you don't want to upgrade your Python version systemwide, I would use virtualenv, which lets you maintain localized python installations that you can source into your environment to use.  And actually, what I might recommend overall is a combination of both: upgrade your python to the latest using apt-get, and install virtualenv to use python 2.7.6 if you have any code that relies on that specific version.

I couldn't get python3 installed on my machine so I couldn't test.  Were you able to get the diawi-cli script to work with python3?

**Comment by theJenix** [comment] 2016-01-28 23:11
Quick update re: Python3.  They appear to have removed urllib2, meaning I'd have to rewrite the whole thing for python3.  Probably not a big deal but I unfortunately don't have time to do it right now.  If you want to do it and submit a pull request, I'll pull it in.

**Comment by theJenix** [comment] 2016-02-17 14:09
It's been a while since the last activity on this and the issue is fixed, so I'm going to close this.  If you are still having issues, please open a new issue or contact me directly if it makes more sense to do so.

**Closed as completed by theJenix** 2016-02-17 14:09 UTC

**Comment by louisdoe** [comment] 2016-02-18 13:15
$apt install python  tells me I have the latest version
$python -V tells me it's 2.7.6

I don't know how to force it to install 2.7.9.

I am not developping in python sorry !

2016-01-29 0:11 GMT+01:00 Jesse Rosalia notifications@github.com:
